language: java

cache:
  directories:
    - "$HOME/.m2"

before_install:
  - chmod +x mvnw
  - sudo apt-get install jq

after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r SharedExpenses-application/target/site/jacoco-aggregate/jacoco.xml

before_cache:
  - rm -rf $HOME/.m2/repository/com/dfernandezaller/SharedExpenses

jdk:
  - openjdk17