name: Maven build CI

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Maven verify
        run: ./mvnw clean verify -B
      - name: Upload coverage data
        if: github.ref == 'refs/heads/master'
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r sharedexpenses-application/target/site/jacoco-aggregate/jacoco.xml